import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Banknote, Building2, HandHeart, UserRoundPlus, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageHero } from "@/components/site/PageHero";
import { InterestForm } from "@/components/site/Forms";
import { trackEvent } from "@/lib/analytics";
const title="Get Involved | Empowering Athletes Legacy",description="Join as an athlete, mentor, volunteer, donor, corporate partner, or community supporter.";
export const Route=createFileRoute("/get-involved")({head:()=>({meta:[{title},{name:"description",content:description},{property:"og:title",content:title},{property:"og:description",content:description},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/get-involved"}]}),component:Page});
const ways=[[UserRoundPlus,"Athletes","Begin a confidential, whole-person journey.","/athlete-pathway"],[UsersRound,"Mentors","Bring wisdom, consistency, and care.","#interest"],[HandHeart,"Volunteers","Offer time and talent where it matters.","#interest"],[Banknote,"Donors","Help fund access, education, and support.","#donate"],[Building2,"Corporate partners","Sponsor a program or contribute expertise.","/partners"]] as const;
function Page(){return <><PageHero eyebrow="Get involved" title="Legacy is built in relationship." intro="There is a meaningful place for athletes, families, mentors, volunteers, donors, organizations, and community supporters."/><section className="bg-ivory py-24 text-ink"><div className="section-shell grid gap-px bg-ink/15 sm:grid-cols-2 lg:grid-cols-5">{ways.map(([Icon,name,text,to])=><article key={name} className="bg-ivory p-6"><Icon className="size-6 text-emerald"/><h2 className="mt-12 font-display text-3xl">{name}</h2><p className="mt-4 min-h-20 text-sm leading-6 text-ink-soft">{text}</p>{to === "/athlete-pathway" ? <Button asChild variant="dark" size="sm"><Link to="/athlete-pathway">Explore <ArrowRight/></Link></Button> : to === "/partners" ? <Button asChild variant="dark" size="sm"><Link to="/partners">Explore <ArrowRight/></Link></Button> : <a href={to} className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.12em] text-emerald">Explore <ArrowRight className="size-4"/></a>}</article>)}</div></section><section id="donate" className="bg-emerald py-20"><div className="section-shell grid gap-10 md:grid-cols-[1fr_auto] md:items-end"><div><p className="eyebrow">Give with purpose</p><h2 className="mt-5 font-display text-5xl">Invest in the person beyond the player.</h2><p className="mt-5 max-w-2xl text-sm leading-7 text-ivory/70">Donation processing will be connected after the organization selects its provider. These amounts are interface placeholders and no charge will occur.</p></div><div className="flex flex-wrap gap-3">{[50,100,250,500].map(a=><Button key={a} variant="gold" onClick={()=>trackEvent("donation_interest",{amount:a})}>${a}</Button>)}</div></div></section><section id="interest" className="py-24"><div className="section-shell grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Mentor or volunteer</p><h2 className="mt-5 font-display text-5xl">Show up with consistency.</h2></div><InterestForm kind="mentor"/></div></section></>}
