import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowDown, ArrowRight, ChevronsRight, Play } from "lucide-react";
import { Button } from "@/components/ui/button";
import { AnimatedCounter, ProgramRail, ScrollProgress, SectionReveal } from "@/components/site/HomeWidgets";
import { LegacyPlayerBuilder } from "@/components/site/LegacyPlayerBuilder";
import { pathway } from "@/content/site";
import { brandMedia, mediaCrops } from "@/content/media";
import { trackEvent } from "@/lib/analytics";
import heroImage from "@/assets/eal-hero.jpg";
import pathwayImage from "@/assets/eal-pathway.jpg";
import heroFilmWebm from "@/assets/Eagles_Practice_Hero.webm.asset.json";
import heroFilmMp4 from "@/assets/Eagles_Practice_Web_Clean.mp4.asset.json";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [{ title: "Empowering Athletes Legacy | Purpose Beyond the Game" }, { name: "description", content: "Enter the EA Legacy ecosystem for faith-centered education, mentorship, and opportunities helping athletes build beyond sports." }, { property: "og:title", content: "Empowering Athletes Legacy | Enter the Legacy" }, { property: "og:description", content: "The game creates the platform. Purpose creates the legacy." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/" }] }), component: HomePage,
});

function HomePage() {
  return <>
    <ScrollProgress />

    <section className="locker-room-hero relative min-h-[92svh] overflow-hidden grain">
      <div className="hero-film-panel" aria-label="EA Legacy organization film panel">
        <video poster={heroImage} autoPlay muted loop playsInline preload="auto" aria-hidden="true" tabIndex={-1} className="size-full object-cover max-md:[object-position:var(--hero-mobile)] md:[object-position:var(--hero-desktop)]" style={{ "--hero-mobile": mediaCrops.heroVideo.mobile, "--hero-desktop": mediaCrops.heroVideo.desktop } as React.CSSProperties} onPlay={() => trackEvent("video_play", { video: "eagles-practice-v1", provider: "ealegacy", placement: "home-locker-film-panel" })}>
          <source src={heroFilmWebm.url} type="video/webm" /><source src={heroFilmMp4.url} type="video/mp4" />
        </video>
        <div className="absolute inset-0 bg-gradient-to-r from-obsidian/55 via-transparent to-obsidian/20" />
      </div>
      <div className="absolute inset-x-[8%] bottom-0 h-[18%] bg-gradient-to-t from-burnt/10 to-transparent [clip-path:polygon(12%_0,88%_0,100%_100%,0_100%)]" aria-hidden="true" />
      <div className="relative mx-auto flex min-h-[92svh] max-w-[1440px] items-end px-5 pb-16 pt-32 md:items-center lg:px-10">
        <div className="max-w-4xl animate-reveal">
          <div className="flex items-center gap-4"><img src={brandMedia.logo} alt="" className="feature-crest size-16 object-contain md:size-20" /><p className="locker-nameplate">01 / Entry Hall</p></div>
          <h1 className="mt-7 max-w-4xl font-display text-5xl leading-[0.88] text-balance md:text-7xl lg:text-[7rem]">The Game Creates the Platform. <span className="text-gold">Purpose Creates the Legacy.</span></h1>
          <p className="mt-7 max-w-xl text-sm leading-7 text-muted-foreground md:text-base">We see the person beyond the player. Build what reaches family, empowers youth, strengthens community, and outlives the game.</p>
          <div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild variant="legacy" size="lg"><Link to="/who-we-are" onClick={() => trackEvent("cta_click", { cta: "explore-mission" })}>Explore the Mission <ArrowRight /></Link></Button><Button asChild variant="glass" size="lg"><Link to="/get-involved">Join the Ecosystem <ArrowRight /></Link></Button></div>
        </div>
      </div>
      <div className="absolute bottom-7 right-8 hidden items-center gap-3 text-[10px] uppercase tracking-[0.2em] text-muted-foreground md:flex"><span>Locker room access</span><span className="relative h-12 w-px overflow-hidden bg-border"><span className="absolute inset-0 bg-burnt animate-scroll" /></span><ArrowDown className="size-3" /></div>
    </section>

    <div className="overflow-hidden border-y border-border bg-burnt py-4"><div className="flex w-max animate-marquee gap-12 text-xs font-semibold uppercase tracking-[0.18em] text-ivory"><span>Education Before Opportunity</span><span>Relationships Before Transactions</span><span>Impact Beyond the Game</span><span>The Athlete Is the Purpose</span><span>Education Before Opportunity</span><span>Relationships Before Transactions</span><span>Impact Beyond the Game</span><span>The Athlete Is the Purpose</span></div></div>

    <section className="mission-wall relative overflow-hidden py-20 md:py-28"><div className="absolute inset-0 perforated-metal opacity-10" aria-hidden="true" /><SectionReveal className="section-shell relative grid gap-10 lg:grid-cols-[.5fr_1.5fr]"><div><p className="locker-nameplate">02 / Mission Wall</p></div><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-gold">Empowering Athletes Legacy</p><h2 className="mt-5 max-w-5xl font-display text-5xl leading-[0.95] md:text-7xl lg:text-8xl">We See the Person <em className="font-normal text-burnt">Beyond the Player.</em></h2><div className="mt-9 grid gap-7 border-t border-ivory/20 pt-7 md:grid-cols-2"><p className="text-xl leading-8">Today’s platform can build tomorrow’s family strength, ownership, service, and generational impact.</p><p className="text-sm leading-7 text-muted-foreground">EA Legacy surrounds professional athletes with trusted education, mentorship, wellness, business development, financial literacy, community partnerships, and opportunity.</p></div></div></SectionReveal></section>

    <section className="relative overflow-hidden border-y border-border bg-charcoal py-20 md:py-28"><div className="absolute inset-0 sport-grid opacity-15" aria-hidden="true" /><SectionReveal className="section-shell relative"><div className="grid gap-8 lg:grid-cols-[.45fr_1.55fr] lg:items-end"><div><p className="locker-nameplate">03 / Film Review</p><h2 className="mt-6 font-display text-5xl leading-none md:text-6xl">Study the mission. See the work.</h2><p className="mt-5 text-sm leading-7 text-muted-foreground">The organization film brings the person, preparation, and purpose into focus.</p></div><div className="film-room-frame relative p-2 md:p-4"><div className="flex items-center justify-between border-b border-border px-3 py-3 text-[9px] font-bold uppercase tracking-[0.16em] text-muted-foreground"><span className="flex items-center gap-2"><Play className="size-3 text-burnt" /> EA Legacy Film Room</span><span>04:38 // Review</span></div><video poster={heroImage} controls playsInline preload="metadata" className="aspect-video w-full bg-obsidian object-contain" aria-label="EA Legacy organization video" onPlay={() => trackEvent("video_play", { video: "eagles-practice-v1", provider: "ealegacy", placement: "home-film-room" })}><source src={heroFilmWebm.url} type="video/webm" /><source src={heroFilmMp4.url} type="video/mp4" /></video></div></div></SectionReveal></section>

    <section className="legacy-builder-section relative overflow-hidden border-b border-border bg-deep py-20 md:py-28"><div className="absolute inset-0 sport-grid opacity-15" aria-hidden="true" /><SectionReveal className="section-shell relative"><div className="mb-10 grid gap-6 lg:grid-cols-[.55fr_1.45fr]"><div><p className="locker-nameplate">04 / EA Legacy Player Builder</p></div><div><h2 className="font-display text-5xl uppercase text-gold md:text-7xl">Build a Legacy Beyond the Game</h2><p className="mt-5 max-w-2xl text-sm leading-7 text-muted-foreground">Create the person, purpose, and platform that will carry your impact beyond your playing career.</p></div></div><LegacyPlayerBuilder /></SectionReveal></section>

    <section className="relative overflow-hidden py-20 md:py-28"><div className="absolute inset-0 perforated-metal opacity-25" aria-hidden="true" /><SectionReveal className="section-shell relative"><p className="locker-nameplate">05 / Program Lockers</p><div className="mt-6 grid gap-5 md:grid-cols-[1fr_.7fr] md:items-end"><h2 className="font-display text-5xl md:text-7xl">Open the right resource.</h2><p className="text-sm leading-7 text-muted-foreground md:justify-self-end">Eight connected locker bays. Select one to illuminate its purpose and next action.</p></div><ProgramRail /></SectionReveal></section>

    <section className="tunnel-path relative overflow-hidden border-y border-border py-20 md:py-28"><img src={pathwayImage} alt="Athletes and mentor walking toward the field" width={1600} height={1008} loading="lazy" className="absolute inset-0 size-full object-cover opacity-10 max-md:[object-position:var(--path-mobile)] md:[object-position:var(--path-desktop)]" style={{ "--path-mobile": mediaCrops.pathway.mobile, "--path-desktop": mediaCrops.pathway.desktop } as React.CSSProperties} /><div className="absolute inset-0 bg-gradient-to-r from-obsidian via-obsidian/95 to-obsidian/70" /><SectionReveal className="section-shell relative"><p className="locker-nameplate">06 / Locker to Tunnel</p><h2 className="mt-6 font-display text-5xl md:text-7xl">Five thresholds. One lasting direction.</h2><div className="mt-12 grid gap-px bg-border lg:grid-cols-5">{pathway.map((stage, index) => <article key={stage.title} className="group relative min-h-64 overflow-hidden bg-background/88 p-6 backdrop-blur-sm transition-colors hover:bg-walnut"><div className="absolute inset-x-0 top-0 h-1 origin-left bg-burnt transition-transform duration-500 group-hover:scale-x-100" /><span className="text-xs text-gold">Threshold {stage.step}</span><ChevronsRight className="mt-8 size-5 text-burnt" /><h3 className="mt-7 font-display text-3xl">{stage.title}</h3><p className="mt-4 text-sm leading-6 text-muted-foreground">{stage.text}</p><span className="absolute bottom-4 right-4 text-[9px] text-muted-foreground">{Math.round(((index + 1) / 5) * 100)}%</span></article>)}</div><Button asChild variant="legacy" size="lg" className="mt-9"><Link to="/athlete-pathway">Walk the pathway <ArrowRight /></Link></Button></SectionReveal></section>

    <section className="bg-charcoal py-20 md:py-28"><SectionReveal className="section-shell"><div className="grid gap-7 md:grid-cols-[1fr_auto] md:items-end"><div><p className="locker-nameplate">07 / Digital Nameplates</p><h2 className="mt-6 font-display text-5xl md:text-7xl">Initial goals. Visible accountability.</h2></div><span className="locker-nameplate">Targets, not achieved results</span></div><div className="mt-12 grid gap-px bg-border sm:grid-cols-2 lg:grid-cols-4">{[[100,"","Athletes engaged"],[80,"%","Action plans completed"],[40,"","Vetted mentors"],[1000,"","Community service hours"]].map(([value,suffix,label], index) => <article key={String(label)} className="digital-panel relative min-h-52 overflow-hidden p-7"><span className="absolute right-4 top-4 text-[9px] uppercase tracking-[0.14em] text-muted-foreground">Initial goal 0{index + 1}</span><strong className="font-display text-6xl text-gold"><AnimatedCounter value={Number(value)} suffix={String(suffix)} /></strong><p className="mt-3 text-sm text-foreground">{label}</p><div className="mt-7 h-px bg-border"><span className="block h-full bg-legacy" style={{ width: `${60 + index * 10}%` }} /></div></article>)}</div><div className="mt-8 text-right"><Link to="/impact" className="inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.15em] text-gold">View the outcomes framework <ArrowRight className="size-4" /></Link></div></SectionReveal></section>

    <section className="final-grid relative min-h-[72vh] overflow-hidden bg-deep grain"><div className="absolute inset-0 sport-grid opacity-30" aria-hidden="true" /><div className="absolute inset-y-0 left-1/2 w-px bg-gradient-to-b from-transparent via-burnt to-legacy shadow-[0_0_24px_var(--burnt)]" aria-hidden="true" /><div className="absolute inset-x-[8%] bottom-0 h-1/2 bg-gradient-to-t from-burnt/15 to-transparent [clip-path:polygon(38%_0,62%_0,100%_100%,0_100%)]" aria-hidden="true" /><div className="final-scan absolute inset-y-0 w-1/2" aria-hidden="true" /><SectionReveal className="section-shell relative flex min-h-[72vh] items-center"><div className="max-w-5xl py-24"><div className="flex items-center gap-4"><img src={brandMedia.logo} alt="" className="feature-crest size-16 object-contain" /><p className="locker-nameplate">08 / The Tunnel</p></div><h2 className="mt-7 font-display text-6xl leading-[.92] md:text-8xl">A Career Has a Timeline. <span className="text-gold">A Legacy Does Not.</span></h2><p className="mt-7 max-w-xl text-sm leading-7 text-muted-foreground">Take the platform you have today and build what generations will remember beyond your sport.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button asChild variant="legacy" size="lg"><Link to="/get-involved">Enter the Ecosystem <ArrowRight /></Link></Button><Button asChild variant="glass" size="lg"><Link to="/contact">Refer an Athlete <ArrowRight /></Link></Button></div></div></SectionReveal></section>
  </>;
}